FROM openjdk:7

# create directories
RUN mkdir /tools

# setup codeql tools
RUN wget -q https://github.com/github/codeql-action/releases/download/codeql-bundle-20210921/codeql-bundle-linux64.tar.gz
RUN tar xzf /codeql-bundle-linux64.tar.gz -C tools

# copy source
COPY src /usr/src/myapp

# set working directory
WORKDIR /usr/src/myapp

# run analysis
RUN ./src/analyse.sh
