name: Sammich Analysis 2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: docker build -f Dockerfile.version2 -t hello-belfast-image .
